### PR TITLE
combine react-native destructuring into import statement

### PR DESCRIPTION
**Pull request by avindra**

### CODE REVIEW

**Comment by gre** [comment]
Thanks for this, that's a good idea.

that's a bit specific to gl-react, but `require("gl-react/react-native")` can't work with import syntax because Babel transpile imports before require() .

An equivalent way is to do `import "gl-react/react-native"`, but don't worry about it for now:
the need to do `require("gl-react/react-native")` will be gone in incoming gl-react-native version that hopefully will be released just after react-native 0.18 (that finally depends on React :) )

**Comment by gre** [comment]
(so i'll probably merge your PR, after releasing this next version)

**Comment by avindra** [comment]
Are you saying that imports are always processed before require()? If so, I learned something new today, thanks!

**Comment by gre** [comment]
yeah I've discovered this. I don't know if it's intentional or not in babel. there must be a reason

**Comment by avindra** [comment]
Makes sense. I think the intention with import/export was to make all loading done statically (i.e., not dynamically), so that tooling could be made to support auto completion, jumping to imported functions easier, etc.

**Comment by gre** [comment]
there were some modification since your PR, but also gl-react should now fully support the import syntax since the React injection hack is no more used :)

feel free to update your PR if you have time for this, otherwise i'll eventually _search and replace_ ;)

Thanks

**Comment by gre** [comment]
this is now fixed in latest master

**Pull request closed without merging**
