### PR TITLE
loadImageWithoutClipping is Depreciated. 

### PR DESCRIPTION
**Pull request by sscaff1**
https://github.com/facebook/react-native/blob/master/Libraries/Image/RCTImageLoader.m#L766

### CODE REVIEW

**Comment by gre** [comment]
Thanks

**Comment by gre** [comment]
can you tell me what version you used? because it doesn't work in react-native 0.27.2 which is latest stable

**Comment by gre** [comment]
looks like it comes from https://github.com/facebook/react-native/commit/ee8496f364070f1b3629b94b347a0e11b2895dec which is for next 0.28 ?

As soon as RN 0.28 is released, I'll release a 2.28, which will be breaking for older RN.

**Comment by sscaff1** [comment]
Sounds good thanks @gre. And yes I was using 0.28

**Pull request merged**
