### PR TITLE
Added @ReactModule annotation for react-native 0.58

### PR DESCRIPTION
**Pull request by southerton81**
As per issue #193

### CODE REVIEW

**Comment by joseguerrerov** [comment]
@gre 👋 can you take a look a this one ? or is this a breaking change for < RN 0.58

**Comment by joseguerrerov** [comment]
🏆 @gre thanks !!

**Comment by mars-lan** [comment]
@gre could you release a new version on npm to include this fix? Thanks.

**Comment by gomdolkim** [comment]
@gre do you have any plan to release new version on npm?

**Comment by shockdesign** [comment]
Can we get a new release cut? Would be helpful.

**Pull request merged**
