### PR TITLE
Fixing snapshot size in android

### PR DESCRIPTION
**Pull request by gullitmiranda**

### CODE REVIEW

**Comment by gre** [comment]
Hi @gullitmiranda ,
could you explain a bit what this fix? I haven't noticed a problem with current implementation but I must have not tested a case.

thanks

**Comment by gullitmiranda** [comment]
on android the size used to take the snapshot is the screen layout of the device instead of the size of the canvas (surface). this causes the captured image to stay with dimensions different from the canvas.

**Comment by gre** [comment]
so if you have a Surface of 300x200 on pixel ratio of 2,
it used to snapshot a 600x400 but with your fix it snapshot a 300x200 ?
need to see if this is consistent with iOS impl

**Comment by gre** [comment]
or is it the reverse of what I say ?

**Comment by gullitmiranda** [comment]
is what you said. on ios it worked perfectly. but it would be nice if you (or anyone else) to also test.

**Comment by gre** [comment]
I actually tend to think the snapshot API should give you the pixel size image, not the more virtual point size. so it's probably to fix in iOS if it's not the case..
If you want it to be resized back to the point size, maybe you should use a resizer like `ImageEditor` ?

**Comment by gre** [comment]
Or simply use pixelRatio=1 on the surface.
My point is the capture should be the raw pixel without any resize. A
direct copy of the underlying gl framebuffer

**Comment by gullitmiranda** [comment]
yes, also think this. the problem is that on android, the canvas has a size, however the capture has another, so, it is generated an image with an incorrect size.

I'm going to do some more tests, it may be necessary to make some improvements in relation to the pixelRation, but I am no Android or Java development, for this, even to find a way to capture the size of the element opengl was not easy for me.

**Comment by superandrew213** [comment]
@gullitmiranda when you say incorrect size, do you mean it's the full image just smaller/bigger or a part of the full image. Not sure if my issue is related to this. But for me on Android the capture is a cropped part of the original image with the filter applied. On iOS everything is working as it should.

**Comment by gullitmiranda** [comment]
no @superandrew213. for me, the screenshot does not have the same size of the canvas (surface).

**Comment by superandrew213** [comment]
This fixes [#123](https://github.com/ProjectSeptemberInc/gl-react-native/issues/123)

**Comment by superandrew213** [comment]
Any updates on this?

**Comment by gre** [comment]
Ok let's merge this, I have not tested much but you are probably right on the inconsistencies across ios / android.

**Pull request merged**
